# Generated by Django 4.2.6 on 2023-10-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web01", "0003_prettynum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prettynum",
            name="price",
            field=models.IntegerField(default=0, verbose_name="价格"),
        ),
    ]
