# Generated by Django 4.2.6 on 2023-10-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web01", "0004_alter_prettynum_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=32, verbose_name="用户名")),
                ("password", models.CharField(max_length=32, verbose_name="密码")),
            ],
        ),
    ]
